version: '3'

services:
  fluentd:
    build:
      context: . # Assuming the Dockerfile is in the current directory
    networks:
      - shared-network
    volumes:
      - ./fluentd.conf:/fluentd/etc/fluent.conf # Assuming the fluentd.conf is in the current directory
    ports:
      - "24224:24224"
      - "24224:24224/udp"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
    networks:
      - shared-network
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
      
  kibana:
    image: docker.elastic.co/kibana/kibana:7.10.1
    networks:
      - shared-network
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

networks:
  shared-network:
    driver: bridge
